logging:
  level:
    root: info
    org:
      jline: error
      apache: error
      reflections: error
      corundumstudio: error
      springframework: error
  file:
    name: "cloud.log"

spring:
  main:
    banner-mode: off

server:
  port: 7401
