logging:
  level:
    root: info
    org:
      jline: error
      apache: error
      reflections: error
      springframework: error
    com:
      corundumstudio: error
    io:
      netty: error
  file:
    name: "cloud.log"

spring:
  main:
    banner-mode: off
  profiles:
    active: production

server:
  port: 7401
